### PR TITLE
CSV data collection

### PR DESCRIPTION
**Pull request by sandfortw**
You can now run rails csv_load:all to pull all the data from the csv files.

### CODE REVIEW

**Review by kassandraleyba — COMMENTED** [review]
nice! looks good.

**Review by sgwalker327 — APPROVED** [review]
Looks good

**Comment by sandfortw** [comment]
I now have it resetting the pk sequence as required in the setup. Just made that change.

**Review by menyeart — COMMENTED** [review]
Setup so far looks great.  Don't see any issues with the rake tasks or tables

**Comment by sandfortw** [comment]
Enums are now up and running.

**Review by kassandraleyba — COMMENTED** [review]
looks great

**Pull request merged**
